name: after_create :blog!
description: Programación y otras yerbas ! 
meta_description: "Cosas nerd, programación, ruby, ROR"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: ""
domain_name: 'http://14tinchov.github.io/'
disqus: true
google_analytics: 'UA-XXXXXXXX-X'
gems: 
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
languages: ["en", "es"]
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]

# Details for the RSS feed generator
url:            'http://after-create.com'
author:         'Martin Villalba'
